### ISSUE TITLE
AXI monitor credit logging

### ISSUE THREAD

**Issue by nijgit** [chipsalliance/aib-protocols#1]
Two issues:

1. ![image](https://user-images.githubusercontent.com/68449348/125988185-8927c5a6-24f2-4727-8868-9b8ae2a807e9.png)

   increases AW credits by 2 instead of 1, can you please check 

2. 
![image](https://user-images.githubusercontent.com/68449348/125988972-c6171b99-4579-4d5c-bc50-216132169391.png)

report the actual credit increment and decrement instead of data bit accumulation

**Comment by johna-eximiusdesign** [comment]
I assume this was a test bug and not anything real. Reopen if this is not the case.
