### ISSUE TITLE
SPI master IP master polling read back wrong data

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#10]
From the sequence you sent to me of master polling:

Reading from the same address (0x0 should not give different value.)
![image](https://user-images.githubusercontent.com/47224718/132409138-2cfeee13-932e-4804-b9d9-cee84c5ebac0.png)

Also read after write of AVMM gives different value:
![image](https://user-images.githubusercontent.com/47224718/132409324-280b77a7-4cb9-45c8-999a-2c40f389abb6.png)

**Comment by johna-eximiusdesign** [comment]
As stated in the meeting, while the busy bit is set the other fields of the control register are not valid. So once the processor begins polling for the busy bit, the other fields should be disregarded until the busy bit is cleared.

**Comment by xinyang2k** [comment]
From user point of view, reading any register value should get correct value no matter what. Any implementation limitation should not be an excuse for the wrong value.

**Comment by johna-eximiusdesign** [comment]
Fixed in 0.8.4 and tested visually.

**Comment by xinyang2k** [comment]
This problem seems gone in 0.8.4.
