### ISSUE TITLE
SPI master soft reset sequence

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#11]
From the sequence I received from Eximius, the soft reset needed from all transactions (All or some?). Question:
1) Is this procedure needed for absolutely any transaction?  User needs to know under which circumstances this is needed.
2) What symptom makes user know they need to do the soft reset?
3) How to prevent user from put this soft reset in wrong time? (Should this after write, or after read, after polling, .... ) How to prevent program error?
4) Looks to me, the soft reset is trying to cover design/implementation caveat.  Can this sequence taking care internally? 
    a) Change FIFO structure to buffer for example. 
    b) Reset by rising edge of ss_n or falling edge of ss_n. 
    c) Block dummy write from slave.

**Comment by xinyang2k** [comment]
If you have to keep FIFO structure, automatically reset the FIFO pointer at the beginning of the SS_N assertion seems cleaner and less confusing to user. (When SPI master command rising edge.)

**Comment by johna-eximiusdesign** [comment]
The soft reset sequence was requested by Intel. It is not required for the design but was included in the delivered sequences as part of the request. It is not required and if you do not want to use it, don't use it.

**Comment by xinyang2k** [comment]
Reopen the issue. Email from your DV. Please let your DV confirmed with the following statement. Also only the issue filer can close the issue subject to verify the fix:
Soft reset sequence is referring to fifo pointer reset only. The previous sequence also had this and with the latest sequence, I added spi slave polling. 

Each read/write operation needs multiple spi transfer and polling to ensure command is completed. Because of the full duplex nature of spi transfer, when ever master is sending the data to slave, master is also receiving the data from slave. This data from the slave could be valid or invalid(dummy). The dummy data must be ignored while reading and must be discarded during read. 
 
To ensure the number of dummy reads is always fixed and known. Fifo pointer soft reset is used.

**Comment by johna-eximiusdesign** [comment]
This was pending per Issue #12. Current answer is same as before, there is no strict need to perform soft resets, but the user may do so for various reasons. See #12 for more details.

**Comment by nij-intel** [comment]
#29 and #11 are duplicates of 12 so closing them
