### ISSUE TITLE
SPI Slave buffer write procedure inquiry 

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#16]
How does SPI slave handle the following:
User program 100 entry to SPI slave write buffer. Then he may realize one entry is wrong and need to correct it. (say entry 3).  What is the right procedure to do that? Can DV show us how to do that? With the current implementation, this can be a daunting process.

**Comment by johna-eximiusdesign** [comment]
The best solution is not to write bad data into the FIFO. But if this does occur, the contents of the Write Buffer can be erased by issuing a soft reset. This should be as simple as writing a 0x3 to 0x44 which should be the write buffer control and the writing 0x0 to the same register.

**Comment by nij-intel** [comment]
Julie please verify and close this issue

**Comment by dkehlet** [comment]
Feature for future consideration.
