### ISSUE TITLE
SPI master mosi outo one cycle late

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#2]
A 32 bit data is sent out to SPI mosi bus from SPI master value 32'h1000_000. Slave expected to latch bit 28 at the 4th rising clock edge.  The test result shows it appears at 5th cycle.
![Capture](https://user-images.githubusercontent.com/47224718/131759383-42ed157e-ee26-45fa-9f17-08d1d5ab5fd2.PNG)

**Comment by johna-eximiusdesign** [comment]
Good find. Fixed in 0.8.2 release
