### ISSUE TITLE
Channel Alignment release 0.8.4 feedback

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#21]
Since this RTL has not been fully verified, so I just provide as feedback:

![image](https://user-images.githubusercontent.com/47224718/133336117-e3fecada-77ca-4a10-905b-b3287264f313.png)

The above RTL code has already added dynamic deskew feature.  When align_fly is high, CA should always try to align correctly. No matter which state it getting wrong.  From the code, in the RX_ERR and RX_DONE state, if alignment error happens at some point, it can not come out and correct itself. Also at state RX_MON, only during align_err_intv condition, it will go to RX_ERR, otherwise, it will be hanged.

In addition, align_fly give user a way out of dead state. User should switch from non-dynamic state to dynamic state by programming align_fly high.  For the detail information, please see issue 7 here:

https://github.com/chipsalliance/aib-protocols/issues/7

**Comment by nij-intel** [comment]
DV input: switch align_fly back and forth to stress test it

**Comment by johna-eximiusdesign** [comment]
The RTL has been updated from the previous comments and checked in as part of 0.8.5, but DV has not completed the testing of this feature.
