### ISSUE TITLE
Add github issues targeted DV testcases

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#24]
Add testcases targeting the checking of specific github issues and add this detail when you are marking a issue fixed.

If it is covered by an existing testcase include this information.

Good examples:

1. align_fly #7 
2. SPI - clear rd_buffer beginning of each transaction #12

**Comment by nij-intel** [comment]
not a showstopper issue

**Comment by dkehlet** [comment]
Agreed on bug verification concept.
