### ISSUE TITLE
Channel Alignment TX Strobing 0.85 check in feedback

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#26]
![image](https://user-images.githubusercontent.com/47224718/134116444-42b92a8a-37a2-46c5-b68f-135063751ede.png)

For file ca_tx_strb, there is an input signal tx_stb_rcvr which is not in the HAS and FS. Just wonder what is the usage of this signal.  My understand is then tx_stb_en, the strobe will be generated. Otherwise won't.  How is user going to use tx_stb_rcvr?

Does the following state machine will dynamically turn on strobe and turn off the strobe and on?

![image](https://user-images.githubusercontent.com/47224718/134116823-9c157ba0-7722-4ee6-a13a-140f33d81960.png)

**Comment by nij-intel** [comment]
Check if there is a test for tx_stb_en for dynamically enable and disable strobe

**Comment by johna-eximiusdesign** [comment]
We have added the target to add a test for toggling tx_stb_en in our internal DV flow. Is there something more that is needed for this issue?

**Comment by xinyang2k** [comment]
From the tx strobing block RTL, I can see you can only do strobe off -> strobe on -> strobe off. But not strobe off -> strobe on -> strobe off -> strob on.  Also, in my opinion, there is no need to have the state machine and tx_stb_rcvr input.  All this block need to do is when tx_stb_en is zero, bypass the original traffic. When tx_stb_en is one, choose the mux output of original traffic + strobing.

**Comment by xinyang2k** [comment]
Here is the state machine in the code that will not satisfy your  "strobe off -> strobe on -> strobe off -> strob on" condition.
![image](https://user-images.githubusercontent.com/47224718/137984883-c81554a5-74ce-49ad-8f16-cd4b3ec4dd8d.png)

![image](https://user-images.githubusercontent.com/47224718/137984934-41359065-fe1a-4602-aed8-91ca6ecf5231.png)

I am closing this case. It is up to you to fix it.
