### ISSUE TITLE
Convert LPIF AIB model to yellow oval based model

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#28]
current LPIF code uses direct instantiation of aib_model_top this need to be moved to yellow oval for aib2.1_to_aib1.0 tests

![image](https://user-images.githubusercontent.com/90720651/134204527-ce8feeac-3669-4fa8-8867-5724ac4262c3.png)

**Comment by johna-eximiusdesign** [comment]
Release 0.9.0.

This has been in progress for a while and I think previous releases had the YO integrated, but I'm now marking it as fixed.
