### ISSUE TITLE
SPI master 0.85 check in feedback

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#29]
The expected fix is soft reset before every transaction and full duplex for every transaction.
Soft reset before every transaction:  I still do not see that implemented completely as expected. It is pretty much as last time. How do you define the beginning of the transaction?  My understanding is that for every low to high of m_cmd[0], you know next transaction will be started. Look at the picture following that highlighted with red circle.  The result show RTL did soft reset at the end of the transaction instead of the beginning. 

![image](https://user-images.githubusercontent.com/47224718/134223853-eb43e1d0-1ab4-4c03-aacf-66c23395a909.png)

If you do plan to implement soft reset before the transaction, will you do that for every transaction?  My understanding is, it will be easier to do that no matter what. unless, you can argue if the FIFO already empty, then you don't need to do that.  What is your plan?

For the full duplex,  for majority of the operation, write_push is on. For some transaction, it is not on.  My understanding is you need to make it always on. That is actually easier for your RTL. Whenever ss_n is low, just do wirte_push for every 32 bit of shifting. See following picture, highlighted places do not have write_push asserted.

![image](https://user-images.githubusercontent.com/47224718/134224751-e3475850-a31c-4392-af37-905dae262867.png)

**Comment by nij-intel** [comment]
#29 and #11 are duplicates of 12 so closing them
