### ISSUE TITLE
[LPIF] Masked issue with Stream ID from DLL not matching parameterized value for protocol

### ISSUE THREAD

**Issue by mjwEE** [chipsalliance/aib-protocols#35]
Current testbench is driving lp_stream = 5 into both DUTs. The case statement used for mapping lp_stream to protocol type defaults to CXL.$/mem for values not encoded in the parameters for protocol type. This is casing pl_stream to drive to 1 when data is received across the link. 

There are two asks here:

- Please add a check to the test environment that will generate a UVM_ERROR if lp_stream value doesn't match one of the parameter values while pl_trdy is high. 
- Please modify the testbench so the parameter matches the stream id used by the VIP.

Observed in 9-21-2021 RTL

**Comment by mjwEE** [comment]
@arta-eximiusdesign How is this progressing?

**Comment by Harshan-eximius** [comment]
We have the stream ID checker fix present in the latest release of synopsys VIP(S-2021.09-3-T-20211123).
