### ISSUE TITLE
[LPIF] TX/RX paths for link widths <x16 not present

### ISSUE THREAD

**Issue by mjwEE** [chipsalliance/aib-protocols#38]
RTL v0.8.6 does not appear to support narrower link width than x16. For AIB 2.0 gen2 alternative widths of x8 and x4 are needed. For gen 1 additional alternative links widths of x2 and x1 are needed.

**Comment by mjwEE** [comment]
All modes must support 512/256/128Gbps. AIB2.0 Gen1 and AIB1.0 must additionally support 64/32Gbps.

**Comment by johna-eximiusdesign** [comment]
Release 0.9.0.

Fixed and uploaded.
