### ISSUE TITLE
Channel Alignment RTL Bug Based on 0.87 check in

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#39]
Bugs I have observed after 0.87 check in:
1. See label 1 below. At the beginning of the simulaiton, fifo_empty and fifo_pempty are not asserted. That is a bug.
2. See label 2. During alignment processing, some FIFOs are full and then dropped. As I said before, whence you see FIFO is full, something is wrong.  
3.  The strobe interval is two small. Only 4 cycle. In practical, this can cause aliasing (The logic will not know which strobe to align and mistakenly aligned wrong strobe  -- the one before or after.) This is especially true when in the middle of reset, when there are many strobing presented among many lanes. Make the intervals 32 cycle for example will be appropriate. 
4. See label 4. Even though there are a couple of lane FIFOs are full, the state machine does not do anything (like soft reset for example.)  This is a good case to show that even in the static mode (align_fly=0). The state machine is not doing reliable job to do real alignment.  Appear from outside, it looks like it works. But whence examine the detail, it not doing much.
5. RX_MON state, the orphan state, is still there not fixed. 

![image](https://user-images.githubusercontent.com/47224718/135168470-cd93ce20-e20a-4449-b678-9546c9f0df9f.png)

**Comment by xinyang2k** [comment]
CA alignment FIFO looks wrong. After full, no read, keep writing, the full flag disappear.  What is this alignment logic doing?

![image](https://user-images.githubusercontent.com/47224718/135176430-90f787ec-6f76-4fb6-a3e5-3e5f80fb9df5.png)

**Comment by xinyang2k** [comment]
The over write pulse is not asserted either.
1. Please describe what is the expected FIFO behavior.: once full, does that trigger any action? Should be full signal sticky? If this happened right at the beginning, should state machine take any action?  What error flag should asserted?
2. Given this is not dynamic alignment, if error like this happen, what is the CA expected behavior?  If reset needed, can you show case that the reset will actually correct this? (Is DV going to test this scenario?) Add description as what is the exact test sequence.

**Comment by johna-eximiusdesign** [comment]
Most of the above concerns are due to the FIFO status signals that are controllable from USER inputs vs internal status which shows actual FIFO usage. Requested DV to update the DV with USER inputs that match the FIFO status.

Added a test case to confirm entering reset exits our error state.

**Comment by johna-eximiusdesign** [comment]
0.8.17 update:
- FIFO watermarks are correct in TB
- strobe interval has been increased and is scaled correctly

I don't believe there are any other bugs here to be corrected, so marking this issue as fixed.
