### ISSUE TITLE
change symbolic link to script - llink/dv/aximm/tb

### ISSUE THREAD

**Issue by nijgit** [chipsalliance/aib-protocols#4]
there is symbolic link in each of the test directory under:

aib-protocols/llink/dv/aximm/tb

git clone done on PCs does not handle this correctly

Change this to a run.scr that calls run script from ../../run

**Comment by johna-eximiusdesign** [comment]
Fixed and delivered to sharepoint as 0.8.3

**Comment by johna-eximiusdesign** [comment]
Postpone closing until SVT resolution

**Comment by nij-intel** [comment]
changed to calling the main script ../../run_tb $*
