### ISSUE TITLE
SPI 0.88 check in bug: Command register bit zero not working. Master polling failure cause hang at first transaction

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#41]
SPI 0.88 check in has failure start from the first transaction.  
The first SPI operation is SPI write. When avmm is doing read for master polling (no write, only read), SPI transaction finished when stransvld_up high for one clock which set cmd[0] to zero. However, there is a we_cmd pulse over write the cmd[0] to high which indicates a new SPI transaction. At this moment, there should not be any we_cmd because avmm interface is patiently to wait for cmd[0] to zero.  This problem cause hang in avmm interface.  You should only have this we_cmd coming from m_avmm_write. Because of this problem, the simulation can not moving on, and I was not able to verify issue 12.
![image](https://user-images.githubusercontent.com/47224718/135360963-ac94707f-272c-46fe-89e5-2be1fb9b6d4d.png)

![image](https://user-images.githubusercontent.com/47224718/135360893-f6883363-b203-43a1-bef4-02c542dd8420.png)

**Comment by ethirajs-eximiusdesign** [comment]
Can you provide a complete waveform dump file from this failing simulation to look/debug this further.   Thanks.

**Comment by xinyang2k** [comment]
I have uploaded spi_test_09292021.tar.gz in the sharepoint to_eximius folder.
After download the tar file, unzip it. Go to aib-phy-hardware/v2.0/rev1/dv_eximius_mspi/spi24_sims. spim_mpolling.vpd.tcl is the waveform signals list. vcdplus.vpd is the dump file.  If you want to re-run the sim, point the file list to your source file.
Let me know if you need more information.

**Comment by ethirajs-eximiusdesign** [comment]
Got it. I'll get back to you.

**Comment by johna-eximiusdesign** [comment]
Should be fixed in 0.8.9

**Comment by xinyang2k** [comment]
The polling is working now in 0.89.
