### ISSUE TITLE
AXI4-MM wrapper TX_online and RX_online connection

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#43]
should be connected to *tx_tranfer_en

![image](https://user-images.githubusercontent.com/90720651/135561386-aea1f9b9-be22-4f2b-80a2-daacf3d20473.png)

**Comment by nij-intel** [comment]
ca_connect.svi needs a similar update, Eximius team aware of this attaching it here for documenting the finding.

While make this change please do thorough review of ca_connect.svi 

![image](https://user-images.githubusercontent.com/90720651/140384836-830a4579-bf82-4628-983d-0f0cf5723cf3.png)

**Comment by johna-eximiusdesign** [comment]
Version 0.8.16 looks like the snippet here, which fixes everything except the M1S2 case.

![Untitled](https://user-images.githubusercontent.com/87096041/140834676-3a88ac84-ce4d-4f55-a5fe-46c437da9267.jpg)

Please provide the hierarchal path for the M1S2 case to extract ms_tx_transfer_en and sl_tx_transfer_en on the master side so we can test autosynchronization in the M1S2 case.

**Comment by johna-eximiusdesign** [comment]
E-mail exchange:

Hey Terry,

So I'm clear, is this what you mean by adding more instances:
ms_tx_transfer_en[0] =  {V1:top_tb.dut_master1.u_aib_top.u_c3aibadapt_wrap_top.u_c3aibadapt_0.c3aibadapt.adapt_rxchnl.rxrst_ctl.rx_hrdrst_hssi_rx_transfer_en}
ms_tx_transfer_en[1] =  {V1:top_tb.dut_master1.u_aib_top.u_c3aibadapt_wrap_top.u_c3aibadapt_1.c3aibadapt.adapt_rxchnl.rxrst_ctl.rx_hrdrst_hssi_rx_transfer_en} ms_tx_transfer_en[2] =  {V1:top_tb.dut_master1.u_aib_top.u_c3aibadapt_wrap_top.u_c3aibadapt_2.c3aibadapt.adapt_rxchnl.rxrst_ctl.rx_hrdrst_hssi_rx_transfer_en}
etc?

Thanks,
John




On Tue, Nov 9, 2021 at 7:08 PM Huang, YunHui <yunhui.huang@intel.com> wrote:
Hi John ::

 

Here is the name for one instance:

 

(Not a typo. For ms, the name rx and tx is switched.)

ms_tx_transfer_en {V1:top_tb.dut_master1.u_aib_top.u_c3aibadapt_wrap_top.u_c3aibadapt_0.c3aibadapt.adapt_rxchnl.rxrst_ctl.rx_hrdrst_hssi_rx_transfer_en}

ms_rx_transfer_en {V1:top_tb.dut_master1.u_aib_top.u_c3aibadapt_wrap_top.u_c3aibadapt_0.c3aibadapt.adapt_txchnl.txrst_ctl.tx_hrdrst_hssi_tx_transfer_en}

 

(Not a typo. For sl. not switched.)

sl_rx_transfer_en {V1:top_tb.dut_master1.u_aib_top.u_c3aibadapt_wrap_top.u_c3aibadapt_0.c3aibadapt.adapt_rxchnl.rxrst_ctl.sr_fabric_rx_transfer_en}

sl_tx_transfer_en {V1:top_tb.dut_master1.u_aib_top.u_c3aibadapt_wrap_top.u_c3aibadapt_0.c3aibadapt.adapt_rxchnl.rxrst_ctl.sr_fabric_tx_transfer_en}

 

They can add more instances for 24 channel in highlighted places.)

Thanks !

Terry

**Comment by johna-eximiusdesign** [comment]
Release 0.9.0.

Added master AIB 1.0 "transfer_en" hierarchical path and tied into existing online signals.

**Comment by nij-intel** [comment]
Should MS_AIB_GEN1 also include the hierarchical path for transfer_en?

![image](https://user-images.githubusercontent.com/90720651/145084093-172087f6-eb07-4b46-9b8d-c637975c7065.png)

**Comment by johna-eximiusdesign** [comment]
Please check this again in 0.9.1.

**Comment by nij-intel** [comment]
MS_AIB_GEN1 branch is replaced with *transfer_en in 0.9.1

![image](https://user-images.githubusercontent.com/90720651/147134046-6a1f1ef1-5468-41e3-929c-bbea8117a4f5.png)
