### ISSUE TITLE
SPI master synthesis show async fifo can not synthesized into M20K and caused huge area. This could be a problem for CA and logic link because aync (or sync) FIFO are shared common component

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#44]
I tried synthesis of SPI master to FPGA S10 with Quartus 20.3.  Since our security IP will use 512 depth FIFO/RAM, I set FIFO depth as 512. Current implementation can not automatically map to M20K and report shows huge area cost:
18K ALM and 33.5K register with 0 M20K.

![image](https://user-images.githubusercontent.com/47224718/135968458-6d1cd22b-81f8-4935-bcb1-f37532d64343.png)

What intel's SPI master report is as the following for comparison:
127 ALM and 244 register with two M20K block memory.

![image](https://user-images.githubusercontent.com/47224718/135968584-638444bc-62e6-4ccd-89b3-e7f5d08098f8.png)

**Comment by johna-eximiusdesign** [comment]
To enable the FPGA synthesis, please set the FPGA macro as is done in the various FPGA scripts including spim, spis, CA and llink. Attached you can see the result of running the checked in design / script for spim. Note the Register usage is ~700 and the ALM is ~400.

![spi_synth2](https://user-images.githubusercontent.com/87096041/136066778-36e71a57-132f-4e58-b6e0-f0b352455c0c.jpg)

Also attached is the same RTL with a 512 deep FIFO. Note there is a modest increase of Register/ALM to ~750/~480, but the total RAM bits increases by 8x.

![spi_synth4](https://user-images.githubusercontent.com/87096041/136066792-94a79ad4-7f28-478d-8f2c-d404ff65dc80.jpg)

**Comment by xinyang2k** [comment]
Just wondering. During simulation, do you turn on FPGA synthesis option as well?  You can make RTL infer FPGA RAM without specifically with FPGA synthesis macro so that you are synthesize and simulating the same set of RTL.

**Comment by xinyang2k** [comment]
Also I have seen the logic with FPGA and non-FPGA are different. Why it is different? Does that affect functionality?

![image](https://user-images.githubusercontent.com/47224718/136075965-bc569d4d-3e49-4d74-ab65-eba3914156e4.png)

**Comment by johna-eximiusdesign** [comment]
The implementation needed to realized FPGA RAMs is not conducive to ASIC realization. Ergo the different coding / resets, etc. They should simulate the same.

**Comment by xinyang2k** [comment]
correction, for intel 512 depth RAM SPI master total gate counts.  (The previous is 256.)  Still use 2 M20K, but it is 32x512 configuration. 

![image](https://user-images.githubusercontent.com/47224718/136111257-9db15bb7-1cd8-4beb-9d8c-7e6025fb18d7.png)

**Comment by dkehlet** [comment]
Closing this for now. We may reopen depending on alpha testing results.
