### ISSUE TITLE
[LPIF] Handshaking Protocol type from device to host adaptor

### ISSUE THREAD

**Issue by mjwEE** [chipsalliance/aib-protocols#48]
LPIF pl_protocol[2:0] on host adaptor must reflect actual protocol mode of device. This requires handshaking across the link. Please add parameter to set protocol mode of device and SB bits to indicate mode of device to host.

**Comment by johna-eximiusdesign** [comment]
Holding off on fixing this until LPIF interface / bugs settle down.

**Comment by johna-eximiusdesign** [comment]
Should be fixed in 0.9.6 drop (probably fixed earlier)

**Comment by nij-intel** [comment]
working on DV now

**Comment by nij-intel** [comment]
dedicated test added Intel to verify

**Comment by johna-eximiusdesign** [comment]
Latest matrix attached.
[LPIF.PL.Protocol.Negotiation.Matrix.xlsx](https://github.com/chipsalliance/aib-protocols/files/8090889/LPIF.PL.Protocol.Negotiation.Matrix.xlsx)

**Comment by johna-eximiusdesign** [comment]
Protocol negotiation testing is in the Feb 18 release.

**Comment by nij-intel** [comment]
Fixed
