### ISSUE TITLE
dv run script cannot find ../../../../../../design

### ISSUE THREAD

**Issue by nijgit** [chipsalliance/aib-protocols#5]
DV run script is is looking for directory design

12 setenv DESIGN          "${SHIP_WORK}/design"
13 setenv LLINK           "${DESIGN}/llink"
14 setenv DV              "${LLINK}/dv"
15 setenv DV_COMMON       "${DV}/common"
16 setenv AXIMM_HOME      "${DV}/aximm"

this does not exist in github tree

**Comment by johna-eximiusdesign** [comment]
Postpone closing until SVT resolution

**Comment by nij-intel** [comment]
fixed in 0.8.3 onwards
