### ISSUE TITLE
Doc issues

### ISSUE THREAD

**Issue by dkehlet** [chipsalliance/aib-protocols#51]
llink_ug.pdf: Please remove "SHIP" from the document title.  Please remove "SHIP IP Core Functional Specification" from the footer.
ca_ug.pdf: Please remove "SHIP" from the document title. Please remove "SHIP IP User Guide" from the footer.
lpif_adapater_ug.pdf: Please correct "adapater" typo in filename. Please remove "SHIP" from the document title. Please remove "SHIP IP User Guide" from the footer.

**Comment by johna-eximiusdesign** [comment]
Updated versions of the three docs are in github. Please confirm they match the expected.
