### ISSUE TITLE
single channel expecting channel skew in configuration

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#53]
/..0.9/llink/dv/aximm/hdl_interconnect/ca_connect.svi, 17
  Undefined macro exists as: 'GLOBAL_MAX_INTER_CH_SKEW'   
  
../0.9/llink/dv/aximm/hdl_interconnect/ca_connect.svi",
  17: token is '`GLOBAL_MAX_INTER_CH_SKEW', column 81
              aib_delay_mem[2*j + 0] = $urandom_range (0, 
  `GLOBAL_MAX_INTER_CH_SKEW); // S2M aka M RX

**Comment by johna-eximiusdesign** [comment]
should be fixed in 0.9.1

**Comment by nij-intel** [comment]
fixed in 0.9.1
