### ISSUE TITLE
AXI4 regression and coverage document

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#54]
I am able to run regression for the alpha cases (i.e M2S1 F2F/F2H) would like to get instructions to run the regression for the full configurations for:

1. AXI4 and AXI4 multi interfaces on one channel
2. AXI4-Stream
3. AXI4-Lite

Please include how to turn on coverage (line/conditional/toggle/branch) on the alpha cases and regression runs

**Comment by johna-eximiusdesign** [comment]
READMEs and scripts exist in the 0.9.2 drop in the llink/dv/aximm and llink/dv/axist repositories.

**Comment by nij-intel** [comment]
Able to run regression with 0.9.3 using *grid* script, this script should be modified for running on local grids. Ended up separating run and results as 2 different scripts.
