### ISSUE TITLE
setup.sh missing for run script

### ISSUE THREAD

**Issue by nijgit** [chipsalliance/aib-protocols#6]
run script using setup.sh which is missing in the tree

13 setenv LLINK           "${DESIGN}/llink"
14 setenv DV              "${LLINK}/dv"
15 setenv DV_COMMON       "${DV}/common"
16 setenv AXIMM_HOME      "${DV}/aximm"

18 setenv LLINK_DUT      "${tbench_dir}/aximm_ll_dut"
19 setenv AXIMM_TB       "${tbench_dir}/.."

21 eval pushd .
22 eval cd ${DESIGN}
23 source ${DESIGN}/setup.sh  <===

**Comment by johna-eximiusdesign** [comment]
Fixed and delivered to sharepoint as 0.8.3

**Comment by johna-eximiusdesign** [comment]
Postpone closing until SVT resolution

**Comment by nij-intel** [comment]
fixed in 0.8.3
