### ISSUE TITLE
CA and LPIF regression and coverage document

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#61]
Need a similar document to AXI4 + scripts to run regression and coverage for CA and LPIF. If you can keep this grid modular/independent like AXI it will be useful.

**Comment by johna-eximiusdesign** [comment]
CA regression document was uploaded in 0.9.6 (and maybe earlier).

**Comment by johna-eximiusdesign** [comment]
Uploaded as part of Feb 18 release.

**Comment by nij-intel** [comment]
Fixed.
