### ISSUE TITLE
Question on PTM_RX_DELAY parameter

### ISSUE THREAD

**Issue by johna-eximiusdesign** [chipsalliance/aib-protocols#62]
Hey Michael,

Earlier today (Thursday) you confirmed that the intent for the pl_ptm_rx_delay[7:0] signal is to be the PTM_RX_DELAY parameter expressed in nanoseconds, where the clock to ns can be gleaned from the LPIF_CLOCK_RATE parameter.

In Gen2 Full rate, this can be in increments of 0.5ns. How do you want us to express that? Round up / down? Or can we assume PTM_RX_DELAY will always be even if we are in Gen2 Full rate?

Related, since pl_ptm_rx_delay[7:0] is 8 bits, that limits the value of PTM_RX_DELAY to 127, 255, or 511 or smaller for Quarter, Half, or Full in Gen2 (and 127, 255 for Half, Full in Gen1). Am I understanding that correctly?

Thanks,
John

**Comment by mjwEE** [comment]
Rounding should be fine. Please round down as that is simpler and this is not intended to be perfectly representative signal. The limits are not making sense to me though. Eight bits is sufficient for representing an integer value between 0 and 255. But in any case the expected values for this link are well under 127. The LogPHY adds a single cycle of latency and the PHY layer will only add a dozen or so more cycles in the worst cases. At 500MHz this still put the reported value at ~30ns worst case.

**Comment by johna-eximiusdesign** [comment]
Had good conversation with Michael earlier and we generally agreed on the above understandings, but Michael did want to think on the pipeline vs PTM ramifications a bit.

I'm marking this as fixed, but I'll leave to Michael to close when he is ready.

**Comment by mjwEE** [comment]
We are aligned. PTM_RX_DELAY should be used for pl_ptm_rx_delay[7:0] and remain independent from LPIF_PIPELINE_DELAY. Closing this issue.
