### ISSUE TITLE
[LPIF] Regression script is broken in 0.9.5 

### ISSUE THREAD

**Issue by mjwEE** [chipsalliance/aib-protocols#65]
While the smoke test is properly defining LPIF_DIE_A_PL_PROTOCOL and LPIF_DIE_B_PL_PROTOCOL macros and running to completion, the regression script is generating configs without these macros defined causing compilation to fail for all test cases.

**Comment by johna-eximiusdesign** [comment]
Fixed in 0.9.6

**Comment by nij-intel** [comment]
Michael is able run nightly so closing this issue. Michael re-open if this is still an issue.
