### ISSUE TITLE
CA regression runs only ca_basic_test

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#67]
Can we include all tests for reach configuration?

![image](https://user-images.githubusercontent.com/90720651/150659718-5c60ecf1-aeed-4a63-92d6-6613be577c80.png)

**Comment by sameer-eximius** [comment]
ca_basic_test has enough and randomized number of transactions from DIE_A to DIE_B and vice versa.
It is mainly the sailrock_cfg.txt file variations that count in this regression when used with ca_basic_test
run_nightly also offers dedicated test-sailrock_cfg.txt pair inclusion for wider coverage of CA features

Kindly recheck with 0.9.7 release

**Comment by nij-intel** [comment]
Duplicate of #77
