### ISSUE TITLE
CA DV randomize number of channels for testing

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#77]
Uses fixed number of channels for testing not covering 1-24 channels.

**Comment by sameer-eximius** [comment]
Latest release  0.9.7 set to cover dedicated sailrocks for each number of channels

**Comment by nij-intel** [comment]
requesting to clean up run_regression.sh

**Comment by nij-intel** [comment]
Able to run the run_regression.sh successfully here, can we add additional tests on top of ca_basic_test

**Comment by nij-intel** [comment]
able to run randomized sailrock configuration with CA on 0.9.8
