### ISSUE TITLE
Channel Alignment DV delay not working

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#8]
There are no skew of total 8 lanes coming to CA die A and CA die B. The Test bench is trying to introduce delay to each channels, but no delay.

**Comment by johna-eximiusdesign** [comment]
This is a DV only comment, so please do not change the subject to indicate anything other than a DV issue.

This has been fixed and should be working in 0.8.5 release.

**Comment by johna-eximiusdesign** [comment]
My mistake. This was done in a local area, but did not make it into my pull. Should be in next drop.

**Comment by xinyang2k** [comment]
I can see there are many changes in the CA DV.  There is no instruction as how to make delay happen (When we say delay, I mean delay skew between two lanes).  If I just follow the README in ca/dv directory:
cmd to run test:
-----------------------------------------------------------------------------------------
1. Go to directory '/design/ca/dv'
2. Use command :   xrun -f ca_tb.args
   This will help run the preset test 'ca_basic_test_c' from the script file 'ca_tb.args'
------------------------------------------------------------------------------------------
I did not see delay skew from simulation right at beginning. If you have any instruction how to make that happen, I can try again.

![image](https://user-images.githubusercontent.com/47224718/134726454-dbcbebc3-db37-468f-8471-741c8f2988bf.png)

**Comment by johna-eximiusdesign** [comment]
Updated 0.8.7 with updated README and changed default simulation to add delay.

**Comment by xinyang2k** [comment]
CA test bench has the updated delay skew for 8 channel. This has been verified. Issue closed.
