### ISSUE TITLE
axi4-mm addr width cover point not correct

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#81]
covergroup aximm_cov;
    aximm_datawidth_cov : coverpoint aximm_cov_datawidth {
      bins aximm_datawidth_bin[] = {32,64,128,256,512};
    }
    **aximm_addrwidth_cov : coverpoint aximm_cov_addrwidth {
      bins aximm_addrwidth_bin[] = {32,64,128,256,512};
    }**

I think this should {32,48} can you please review rest of the cover points to make sure it is aligning with DUT

**Comment by johna-eximiusdesign** [comment]
Fixed in 0.9.8 drop

**Comment by nij-intel** [comment]
aximm_addrwidth_cov : coverpoint aximm_cov_addrwidth {
      bins aximm_addrwidth_bin[] = {32,64};
    }

should include 48?

**Comment by nij-intel** [comment]
fixed in 1.0
