### ISSUE TITLE
[1.0] CA run_nightly.sh error

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#83]
./eximius/1.0/ca/dv
**python3: can't open file 'run_all_sim.py': [Errno 2] No such file or directory
.a/eximius/1.0/ca/dv/scripts
./run_nightly.sh: line 43: cd: scripts: No such file or directory**
 Generate Directory ./eximius/1.0/ca/dv/scripts/../nightly/M2S2_GEN2_F2F_align_error_fifo16
 Using config file ./eximius/1.0/ca/dv/scripts/../examples/M2S2_GEN2_F2F_align_error_fifo16_sailrock_cfg.txt
 Using ./eximius/1.0/ca/dv/scripts/../nightly/M2S2_GEN2_F2F_align_error_fifo16
 == Finished ==

**Comment by johna-eximiusdesign** [comment]
I am not seeing that error even when I untar the delivered repo. I know you modify the run_nightly.sh script so you can run it locally. Can you check if the error is there.

**Comment by nij-intel** [comment]
I am able to reproduce this consistently. Sending dv script over email

**Comment by johna-eximiusdesign** [comment]
Nij was correct, there was a typo in the script. I missed it initially because it didn't happen where it was reported due to subtle differences in the "ls" command between sites. Fixed and uploaded in 1.0.1.

**Comment by nij-intel** [comment]
fixed in 1.0.1
