### ISSUE TITLE
make run in axi4-st/full_examples/sims/tb_mf2.1_sh1_d256 failed

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#89]
Here is the error message for make run:

![image](https://user-images.githubusercontent.com/47224718/172954835-ecb02b04-a954-41f4-b4e0-8b316ade3864.png)

**Comment by xinyang2k** [comment]
The problem is due to the window character at the end of the line. 
Open the script with Notepad++. view->show symbol-> show all characters:
![image](https://user-images.githubusercontent.com/47224718/173152401-82456836-2e78-4fc3-b358-c1b3b9b00d75.png)

use dos2unix this script  can fix the problem. Please clean that and upload the file again.

**Comment by nij-intel** [comment]
re-open fix not checked in yet

**Comment by nij-intel** [comment]
Fixed in release 1.2: corrected the configuration and not generating strobe from CA for assymetric mode

**Comment by nij-intel** [comment]
Verified
