### ISSUE TITLE
channel alignment  ca_tx_strb hardcode issue

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#9]
Please clarify why hardcode of the highlighted is necessary:
![image](https://user-images.githubusercontent.com/47224718/131783539-21e83be3-3509-44a6-adaa-ca8cd031443d.png)

**Comment by johna-eximiusdesign** [comment]
The module was a common one and was used in other blocks, that is why there are constants. This is hardly a blocking issue and the RTL will simulate and synthesis correctly.
