### ISSUE TITLE
AXI and LPIF tests need to use latest AIB 2.0 RTL

### ISSUE THREAD

**Issue by dkehlet** [chipsalliance/aib-protocols#90]
Current tests use:
  export AIB_ROOT=${PROJ_DIR}/../aib-phy-hardware
  export RTL_ROOT=${AIB_ROOT}/v2.0/rev1/rtl

The tests need to use the BCA RTL at
  v2.0/rev1.1/rtl
This may require a small amount of porting, e.g. adding ports to instantiation of AIB.

**Comment by nij-intel** [comment]
AXI4 done, working on LPIF update

**Comment by nij-intel** [comment]
LPIF update done
